export const jobs = [
  {
    title: "Senior Full Stack Developer",
    description:
      "We are seeking an experienced Full Stack Developer to join our growing team. You will be responsible for developing and maintaining web applications, collaborating with cross-functional teams, and mentoring junior developers.",
    requirements: [
      "5+ years experience with JavaScript/TypeScript",
      "Strong knowledge of React and Node.js",
      "Experience with MongoDB and RESTful APIs",
      "Excellent problem-solving skills",
      "Strong communication abilities",
    ],
    salary: 120000,
    experienceLevel: 5,
    location: "San Francisco, CA",
    jobType: "Full-time",
    position: 1,
    company: "507f1f77bcf86cd799439011",
    createdBy: "507f1f77bcf86cd799439012",
    applications: ["507f1f77bcf86cd799439013", "507f1f77bcf86cd799439014"],
  },
  {
    title: "UX/UI Designer",
    description:
      "Join our creative team as a UX/UI Designer. You'll be responsible for creating intuitive user interfaces, conducting user research, and collaborating with developers to implement designs.",
    requirements: [
      "3+ years of UX/UI design experience",
      "Proficiency in Figma and Adobe Creative Suite",
      "Experience with user research and testing",
      "Strong portfolio demonstrating UI design skills",
      "Knowledge of current design trends and best practices",
    ],
    salary: 95000,
    experienceLevel: 3,
    location: "New York, NY",
    jobType: "Full-time",
    position: 2,
    company: "507f1f77bcf86cd799439015",
    createdBy: "507f1f77bcf86cd799439016",
    applications: ["507f1f77bcf86cd799439017"],
  },
  {
    title: "DevOps Engineer",
    description:
      "Looking for a skilled DevOps Engineer to help streamline our development and deployment processes. You'll be responsible for maintaining our cloud infrastructure and implementing CI/CD pipelines.",
    requirements: [
      "4+ years of DevOps experience",
      "Strong knowledge of AWS or Azure",
      "Experience with Docker and Kubernetes",
      "Proficiency in Python or Go",
      "Understanding of security best practices",
    ],
    salary: 130000,
    experienceLevel: 4,
    location: "Seattle, WA",
    jobType: "Remote",
    position: 3,
    company: "507f1f77bcf86cd799439018",
    createdBy: "507f1f77bcf86cd799439019",
    applications: [],
  },
  {
    title: "Product Marketing Manager",
    description:
      "We're seeking a Product Marketing Manager to develop and execute marketing strategies for our SaaS products. You'll work closely with product teams to craft compelling narratives and drive product adoption.",
    requirements: [
      "4+ years of product marketing experience",
      "Experience in SaaS industry",
      "Strong analytical and strategic thinking skills",
      "Excellent written and verbal communication",
      "Experience with market research and analysis",
    ],
    salary: 110000,
    experienceLevel: 4,
    location: "Austin, TX",
    jobType: "Hybrid",
    position: 4,
    company: "507f1f77bcf86cd799439020",
    createdBy: "507f1f77bcf86cd799439021",
    applications: [
      "507f1f77bcf86cd799439022",
      "507f1f77bcf86cd799439023",
      "507f1f77bcf86cd799439024",
    ],
  },
  {
    title: "Machine Learning Engineer",
    description:
      "Join our AI team as a Machine Learning Engineer. You'll be developing and deploying machine learning models, working with big data, and helping to drive innovation in our products.",
    requirements: [
      "Masters or PhD in Computer Science or related field",
      "Strong background in machine learning algorithms",
      "Experience with PyTorch or TensorFlow",
      "Proficiency in Python and SQL",
      "Experience with deploying ML models to production",
    ],
    salary: 145000,
    experienceLevel: 5,
    location: "Boston, MA",
    jobType: "Full-time",
    position: 5,
    company: "507f1f77bcf86cd799439025",
    createdBy: "507f1f77bcf86cd799439026",
    applications: ["507f1f77bcf86cd799439027"],
  },
];
